# Generated by Django 5.1.2 on 2024-11-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_post_like_count_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_caption',
            field=models.CharField(default='Photo by Blog', max_length=100),
        ),
    ]
